Retrieving zones added and all hosts from all projects.
KohlsTechnology/ansible pull request #2
Opened 2017-06-20 09:51 UTC by mateusz-szczyrzyca

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - New Module Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

##### ANSIBLE VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2017-06-20 10:04 UTC, bart2 commented on contrib/inventory/gce_googleapiclient.py
> +    for project in projects:
we can do:
```
for project in get_all_projects():
```

2017-06-20 10:09 UTC, bart2 reviewed
small code enhancement

2017-06-27 12:59 UTC, maurofaccenda requested changes

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +    --account ACCOUNT_NAME --account=ACCOUNT    Account billing name
use either `ACCOUNT_NAME` or `ACCOUNT` on both. also 'Account billing name' -> 'Billing account name'

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +def get_all_billing_projects(account_billing_name, api_version='v1'):
`account_billing_name` doesn't make sense. use `billing_account_name` instead.

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +    request = service.billingAccounts().projects().list(name=account_billing_name)
same as before.

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +        for projectBillingInfo in response['projectBillingInfo']:
variable name should not have UPPER CASE characters, replace `projectBillingInfo` with `project_billing_info`.
i know it was like that on the sample i've shared with you, but it was already fixed on mine.

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +    account_billing_name = args['--account']
same with `account_billing_name`.

2017-06-27 12:59 UTC, maurofaccenda commented on contrib/inventory/get_all_available_instances.go
> +package main
why this .go file?

2017-06-27 13:27 UTC, maurofaccenda approved these changes

2017-06-27 13:27 UTC, maurofaccenda commented on contrib/inventory/gce_googleapiclient.py
> +    --account ACCOUNT_NAME --account=ACCOUNT_NAME  Account billing name
Account billing name -> Billing account name

2017-06-27 13:30 UTC, maurofaccenda approved these changes

2017-06-27 13:31 UTC, merged